/* eslint-disable import/prefer-default-export */

// MARKERS ACTION TYPES
export const LOAD_MARKERS_PENDING = 'LOAD_MARKERS_PENDING';
export const LOAD_MARKERS_SUCCESS = 'LOAD_MARKERS_SUCCESS';
export const LOAD_MARKERS_FAILED = 'LOAD_MARKERS_FAILED';
export const MARKER_SELECTED = 'MARKER_SELECTED';

// SETTINGS
export const SETTINGS_SHOW_MARKERS_CHANGED = 'SETTINGS_SHOW_MARKERS_CHANGED';
